name: Analyze Terraform Files

on: 
  push:
    branches:
      - main
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  analyze-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find and count Terraform resources
        id: count_resources  # Asigna un ID al step para referenciarlo después
        run: |
          # Buscar todos los archivos .tf en el repositorio
          find . -name "*.tf" > tf_files.txt
          
          # Mostrar la lista de archivos encontrados
          echo "Archivos .tf encontrados:"
          cat tf_files.txt
          
          # Contar los recursos diferentes de Terraform
          resource_count=$(grep -oh -E 'resource "(.*?)"' $(cat tf_files.txt) | sort | uniq -c)
          
          echo "Conteo de recursos de Terraform:"
          echo "$resource_count"
          
          # Contar el número total de tipos de recursos diferentes
          unique_resource_types=$(grep -oh -E 'resource "(.*?)"' $(cat tf_files.txt) | sort | uniq | wc -l)
          
          echo "Número total de tipos de recursos diferentes: $unique_resource_types"
          
          # Guardar el conteo en un archivo
          echo "$resource_count" > resource_count.txt
          
          # Establecer la salida usando un Environment File
          echo "UNIQUE_RESOURCE_TYPES=$unique_resource_types" >> $GITHUB_ENV

  package-results:
    runs-on: ubuntu-latest
    needs: analyze-terraform  # Este job depende del job anterior
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip the results
        run: |
          # Crear un archivo ZIP con el resultado del análisis
          zip terraform_analysis.zip resource_count.txt
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-analysis
          path: terraform_analysis.zip
